name: book_read
description: Create personal tasks, or share them with others.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0+1
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+6
  firebase_core: ^0.4.0+9
  email_validator: ^1.0.0
  image_picker: ^0.6.1+10
  firebase_storage: ^3.0.6
  connectivity: ^0.4.5+2
  flushbar: ^1.9.1
  google_sign_in: ^4.0.11
  intl: ^0.16.0
  flutter_slidable: ^0.5.4
  search_widget: ^0.2.0
  vibration: ^1.1.0
  simple_animations: ^1.3.4
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: ^8.5.0
  badges: ^1.1.0
  circular_bottom_navigation: ^1.0.1
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.2
  flutter_advanced_networkimage: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
